kind: Ingress
apiVersion: networking.k8s.io/v1
metadata: 
  name: guestbook-ui
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: guestbook.gitops.20.62.244.72.nip.io
      http:
        paths: 
          - path: / 
            backend: 
              serviceName: guestbook-ui
              servicePort: 80      